# Generated by Django 4.2.16 on 2024-10-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsageTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(max_length=250, null=True)),
                ('ordering_type', models.CharField(choices=[('A', 'Type A'), ('B', 'Type B')], max_length=50, null=True)),
            ],
        ),
    ]
