# Generated by Django 4.2.16 on 2024-10-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('news_id', models.CharField(max_length=150, unique=True)),
                ('position', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('points', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
